# Generated by Django 4.1.2 on 2022-10-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0002_rename_birth_year_person_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='firstname',
        ),
    ]
